#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const THIS_FILE = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(THIS_FILE), '..');
const INDEX_PATH = path.join(ROOT, 'works/index.json');

const STR = {
  en: {
    title: 'GPT Image 2 Hub · AI Image Inspiration Atlas',
    tagline: 'A curated atlas of GPT Image 2 generations. Every work ships with its full prompt — copy and remix.',
    stats: (t, p, i) => `**${t} topics · ${p} packages · ${i} works**`,
    langToggle: '[简体中文](./README.zh-CN.md)',
    toc: 'Topics',
    promptLabel: '📋 Prompt',
    siteHint: 'Online gallery',
    footer: 'Generated by `npm run readme:gen`',
  },
  'zh-CN': {
    title: 'GPT Image 2 Hub · AI 视觉灵感图鉴',
    tagline: '一份精选的 GPT Image 2 作品集 · 每张图都附完整提示词 · 可直接复制复用。',
    stats: (t, p, i) => `**${t} 主题 · ${p} 合集 · ${i} 作品**`,
    langToggle: '[English](./README.md)',
    toc: '分类',
    promptLabel: '📋 完整提示词',
    siteHint: '在线画廊',
    footer: '由 `npm run readme:gen` 自动生成',
  },
};

function readIndex() {
  return JSON.parse(fs.readFileSync(INDEX_PATH, 'utf8'));
}

function variantUrl(imagePath) {
  const noExt = String(imagePath).replace(/\.(png|jpg|jpeg|webp)$/i, '');
  return `./${noExt.replace(/^\.?\//, '')}.w400.webp`;
}

function loadPrompt(metaPath) {
  try {
    const meta = JSON.parse(fs.readFileSync(path.join(ROOT, metaPath), 'utf8'));
    return (meta.prompt || '').trim();
  } catch {
    return '';
  }
}

function localized(obj, field, lang) {
  return obj?.i18n?.[lang]?.[field]
    || obj?.i18n?.en?.[field]
    || obj?.i18n?.['zh-CN']?.[field]
    || obj?.[field]
    || '';
}

function slugAnchor(str) {
  return String(str).toLowerCase().replace(/[^a-z0-9一-龥\s-]/g, '').trim().replace(/\s+/g, '-');
}

function escapeHtml(str) {
  return String(str).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
}

function render(lang) {
  const idx = readIndex();
  const s = STR[lang];
  const topics = idx.topics || [];
  const imagesByTopic = new Map();
  for (const img of idx.images || []) {
    if (!imagesByTopic.has(img.topic_id)) imagesByTopic.set(img.topic_id, []);
    imagesByTopic.get(img.topic_id).push(img);
  }

  const lines = [];
  lines.push(`# ${s.title}`);
  lines.push('');
  lines.push(`${s.tagline}`);
  lines.push('');
  lines.push(`${s.stats(idx.stats?.topic_count || 0, idx.stats?.package_count || 0, idx.stats?.image_count || 0)} · ${s.langToggle}`);
  lines.push('');

  const topicsWithImages = topics.filter((t) => (imagesByTopic.get(t.id) || []).length > 0);

  lines.push(`## ${s.toc}`);
  lines.push('');
  for (const topic of topicsWithImages) {
    const title = localized(topic, 'title', lang);
    const count = (imagesByTopic.get(topic.id) || []).length;
    lines.push(`- [${title}](#${slugAnchor(title)}) · ${count}`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const topic of topicsWithImages) {
    const topicTitle = localized(topic, 'title', lang);
    const topicDesc = localized(topic, 'description', lang);
    const imgs = (imagesByTopic.get(topic.id) || []).slice().sort((a, b) => {
      const ao = Number(a.generation?.order ?? 0);
      const bo = Number(b.generation?.order ?? 0);
      return ao - bo || String(a.id).localeCompare(String(b.id));
    });

    lines.push(`## ${topicTitle}`);
    lines.push('');
    if (topicDesc) {
      lines.push(`> ${topicDesc}`);
      lines.push('');
    }

    lines.push('<table>');
    for (let i = 0; i < imgs.length; i += 3) {
      lines.push('<tr>');
      for (let j = i; j < i + 3; j += 1) {
        if (j >= imgs.length) {
          lines.push('<td width="33%"></td>');
          continue;
        }
        const img = imgs[j];
        const imgTitle = localized(img, 'title', lang) || img.id;
        const imgUrl = variantUrl(img.image);
        const prompt = loadPrompt(img.meta_path);
        lines.push('<td width="33%" valign="top" align="center">');
        lines.push('');
        lines.push(`<a href="${variantUrl(img.image).replace('.w400.webp', '.w1600.webp')}"><img src="${imgUrl}" width="100%" alt="${escapeHtml(imgTitle)}"/></a>`);
        lines.push('');
        lines.push(`<b>${escapeHtml(imgTitle)}</b>`);
        lines.push('');
        lines.push(`<details><summary>${s.promptLabel}</summary>`);
        lines.push('');
        lines.push('```');
        lines.push(prompt);
        lines.push('```');
        lines.push('');
        lines.push('</details>');
        lines.push('');
        lines.push('</td>');
      }
      lines.push('</tr>');
    }
    lines.push('</table>');
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(`<sub>${s.footer}</sub>`);
  lines.push('');

  return lines.join('\n');
}

const outputs = [
  { file: 'README.md', lang: 'en' },
  { file: 'README.zh-CN.md', lang: 'zh-CN' },
];

for (const { file, lang } of outputs) {
  const md = render(lang);
  fs.writeFileSync(path.join(ROOT, file), md);
  console.log(`wrote ${file} (${md.length} chars · ${lang})`);
}
