#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const THIS_FILE = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(THIS_FILE), '..');
const INDEX_PATH = path.join(ROOT, 'works/index.json');
const SITE_URL = 'https://gpt-image-2-hub-seven.vercel.app';
const TIERS = [9, 6, 3];

const STR = {
  en: {
    title: 'GPT Image 2 Hub · AI Image Inspiration Atlas',
    tagline: 'A curated atlas of GPT Image 2 generations. Every work ships with its full prompt — copy and remix.',
    stats: (t, p, i) => `**${t} topics · ${p} packages · ${i} works**`,
    langToggle: '[简体中文](./README.zh-CN.md)',
    footer: 'Generated by `npm run readme:gen`',
  },
  'zh-CN': {
    title: 'GPT Image 2 Hub · AI 视觉灵感图鉴',
    tagline: '一份精选的 GPT Image 2 作品集 · 每张图都附完整提示词 · 可直接复制复用。',
    stats: (t, p, i) => `**${t} 主题 · ${p} 合集 · ${i} 作品**`,
    langToggle: '[English](./README.md)',
    footer: '由 `npm run readme:gen` 自动生成',
  },
};

function readIndex() {
  return JSON.parse(fs.readFileSync(INDEX_PATH, 'utf8'));
}

function variantUrl(imagePath) {
  const noExt = String(imagePath).replace(/\.(png|jpg|jpeg|webp)$/i, '');
  return `./${noExt.replace(/^\.?\//, '')}.w400.webp`;
}

function localized(obj, field, lang) {
  return obj?.i18n?.[lang]?.[field]
    || obj?.i18n?.en?.[field]
    || obj?.i18n?.['zh-CN']?.[field]
    || obj?.[field]
    || '';
}

function slugAnchor(str) {
  return String(str).toLowerCase().replace(/[^a-z0-9一-龥\s-]/g, '').trim().replace(/\s+/g, '-');
}

function escapeHtml(str) {
  return String(str).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
}

function topicHref(topicId) {
  return `${SITE_URL}/#t-${encodeURIComponent(topicId)}`;
}

function imageHref(imageId) {
  return `${SITE_URL}/#m-${encodeURIComponent(imageId)}`;
}

function tierLimit(count) {
  return TIERS.find((n) => count >= n) ?? 0;
}

function sortTopics(a, b) {
  const ao = Number(a.display?.sort_order ?? Number.POSITIVE_INFINITY);
  const bo = Number(b.display?.sort_order ?? Number.POSITIVE_INFINITY);
  if (ao !== bo) return ao - bo;
  return localized(a, 'title', 'en').localeCompare(localized(b, 'title', 'en'));
}

function render(lang) {
  const idx = readIndex();
  const s = STR[lang];
  const topics = idx.topics || [];
  const categoryDefs = idx.categories?.category || {};
  const categoryOrder = Object.keys(categoryDefs);
  const imagesByTopic = new Map();
  for (const img of idx.images || []) {
    if (!imagesByTopic.has(img.topic_id)) imagesByTopic.set(img.topic_id, []);
    imagesByTopic.get(img.topic_id).push(img);
  }

  const lines = [];
  lines.push(`# ${s.title}`);
  lines.push('');
  lines.push(`${s.tagline}`);
  lines.push('');
  lines.push(`${s.stats(idx.stats?.topic_count || 0, idx.stats?.package_count || 0, idx.stats?.image_count || 0)} · ${s.langToggle}`);
  lines.push('');

  const topicsWithImages = topics.filter((t) => tierLimit((imagesByTopic.get(t.id) || []).length) > 0);
  const topicsByCategory = new Map();
  for (const topic of topicsWithImages) {
    const categoryId = topic.category || 'illustration';
    if (!topicsByCategory.has(categoryId)) topicsByCategory.set(categoryId, []);
    topicsByCategory.get(categoryId).push(topic);
  }

  for (const categoryId of categoryOrder) {
    const categoryTopics = (topicsByCategory.get(categoryId) || []).slice().sort(sortTopics);
    if (!categoryTopics.length) continue;

    const category = categoryDefs[categoryId] || {};
    const categoryLabel = category.labels?.[lang]
      || category.labels?.en
      || categoryId;
    const icon = category.icon || '';

    lines.push(`## ${icon} ${categoryLabel}`.trim());
    lines.push('');

    for (const topic of categoryTopics) {
      const topicTitle = localized(topic, 'title', lang);
      const topicDesc = localized(topic, 'description', lang);
      const originalCount = (imagesByTopic.get(topic.id) || []).length;
      const imgs = (imagesByTopic.get(topic.id) || [])
        .slice()
        .sort((a, b) => {
          const ao = Number(a.generation?.order ?? 0);
          const bo = Number(b.generation?.order ?? 0);
          return ao - bo || String(a.id).localeCompare(String(b.id));
        })
        .slice(0, tierLimit(originalCount));

      lines.push(`### [${topicTitle}](${topicHref(topic.id)}) · ${originalCount}`);
      lines.push('');
      if (topicDesc) {
        lines.push(`> ${topicDesc}`);
        lines.push('');
      }

      lines.push('<table>');
      for (let i = 0; i < imgs.length; i += 3) {
        lines.push('<tr>');
        for (let j = i; j < i + 3; j += 1) {
          if (j >= imgs.length) {
            lines.push('<td width="33%"></td>');
            continue;
          }
          const img = imgs[j];
          const imgTitle = localized(img, 'title', lang) || img.id;
          const imgUrl = variantUrl(img.image);
          const liveImageHref = imageHref(img.id);
          const alt = img.display?.alt?.[lang]
            || img.display?.alt?.en
            || img.display?.alt?.['zh-CN']
            || imgTitle;
          lines.push('<td width="33%" valign="top" align="center">');
          lines.push('');
          lines.push(`<a href="${liveImageHref}"><img src="${imgUrl}" width="100%" alt="${escapeHtml(alt)}"/></a>`);
          lines.push('');
          lines.push(`<b><a href="${liveImageHref}">${escapeHtml(imgTitle)}</a></b>`);
          lines.push('');
          lines.push('</td>');
        }
        lines.push('</tr>');
      }
      lines.push('</table>');
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push(`<sub>${s.footer}</sub>`);
  lines.push('');

  return lines.join('\n');
}

const outputs = [
  { file: 'README.md', lang: 'en' },
  { file: 'README.zh-CN.md', lang: 'zh-CN' },
];

for (const { file, lang } of outputs) {
  const md = render(lang);
  fs.writeFileSync(path.join(ROOT, file), md);
  console.log(`wrote ${file} (${md.length} chars · ${lang})`);
}
